const { Permissions } = require("discord.js")

const PermsArray = [
  `${Permissions.FLAGS.CREATE_INSTANT_INVITE}`,
  `${Permissions.FLAGS.KICK_MEMBERS}`,
  `${Permissions.FLAGS.BAN_MEMBERS}`,
  `${Permissions.FLAGS.ADMINISTRATOR}`,
  `${Permissions.FLAGS.MANAGE_CHANNELS}`,
  `${Permissions.FLAGS.MANAGE_GUILD}`,
  `${Permissions.FLAGS.ADD_REACTIONS}`,
  `${Permissions.FLAGS.VIEW_AUDIT_LOG}`,
  `${Permissions.FLAGS.PRIORITY_SPEAKER}`,
  `${Permissions.FLAGS.STREAM}`,
  `${Permissions.FLAGS.VIEW_CHANNEL}`,
  `${Permissions.FLAGS.SEND_MESSAGES}`,
  `${Permissions.FLAGS.SEND_TTS_MESSAGES}`,
  `${Permissions.FLAGS.MANAGE_MESSAGES}`,
  `${Permissions.FLAGS.EMBED_LINKS}`,
  `${Permissions.FLAGS.ATTACH_FILES}`,
  `${Permissions.FLAGS.READ_MESSAGE_HISTORY}`,
  `${Permissions.FLAGS.MENTION_EVERYONE}`,
  `${Permissions.FLAGS.USE_EXTERNAL_EMOJIS}`,
  `${Permissions.FLAGS.VIEW_GUILD_INSIGHTS}`,
  `${Permissions.FLAGS.CONNECT}`,
  `${Permissions.FLAGS.SPEAK}`,
  `${Permissions.FLAGS.MUTE_MEMBERS}`,
  `${Permissions.FLAGS.DEAFEN_MEMBERS}`,
  `${Permissions.FLAGS.MOVE_MEMBERS}`,
  `${Permissions.FLAGS.USE_VAD}`,
  `${Permissions.FLAGS.CHANGE_NICKNAME}`,
  `${Permissions.FLAGS.MANAGE_NICKNAMES}`,
  `${Permissions.FLAGS.MANAGE_ROLES}`,
  `${Permissions.FLAGS.MANAGE_WEBHOOKS}`,
  `${Permissions.FLAGS.MANAGE_EMOJIS_AND_STICKERS}`,
  `${Permissions.FLAGS.USE_APPLICATION_COMMANDS}`,
  `${Permissions.FLAGS.REQUEST_TO_SPEAK}`,
  `${Permissions.FLAGS.MANAGE_THREADS}`,
  `${Permissions.FLAGS.USE_PUBLIC_THREADS}`,
  `${Permissions.FLAGS.CREATE_PUBLIC_THREADS}`,
  `${Permissions.FLAGS.USE_PRIVATE_THREADS}`,
  `${Permissions.FLAGS.CREATE_PRIVATE_THREADS}`,
  `${Permissions.FLAGS.USE_EXTERNAL_STICKERS}`,
  `${Permissions.FLAGS.SEND_MESSAGES_IN_THREADS}`,
  `${Permissions.FLAGS.START_EMBEDDED_ACTIVITIES}`,
]

module.exports = PermsArray
